### ISSUE TITLE
GetEnvValue - Add support for content from git repositories

### ISSUE THREAD

**Issue by moshloop** [flanksource/kommons#85]
Support retrieving the contents of a file via Git through Flux's git repository - First find the git repository and then using the URL in the status download the file

```yaml
- valueFrom:
      git:
          name: repo 
          namespace: flux-system
          path:  "path/to/file.txt"
```
